export default function getRoleName(roleID: number) {
    switch (roleID) {
        case 1:
            return 'Striker'
        case 2:
            return 'Defender'
        case 3:
            return 'Fast-Talker'
        case 4:
            return 'Feinter'
        case 5:
            return 'Fodder'
        case 6:
            return 'Sandbagger'
        case 7:
            return 'Corruptor'
        case 8:
            return 'Gaslighter'
        case 9:
            return 'Enabler'
        case 10:
            return 'Opportunist'
        case 11:
            return 'Artillery'
        case 12:
            return 'Brute'
        case 13:
            return 'Captain'
        case 14:
            return 'Controller'
        case 15:
            return 'Defender'
        case 16:
            return 'Duelist'
        case 18:
            return 'Fodder'
        case 19:
            return 'Shock'
        case 20:
            return 'Skirmisher'
        case 21:
            return 'Solo'
        case 22:
            return 'Hunter'
        case 23:
            return 'Prey'
        case 24:
            return 'Controller'
        case 25:
            return 'Lock'
        case 27:
            return 'Antagonist'
        case 28:
            return 'Trap'
        case 29:
            return 'Hazard'
        case 30:
            return 'Fodder'
        case 31:
            return 'Elite'
        case 32:
            return 'Elite'
        case 33:
            return 'Solo'
        case 34:
            return 'Elite'
        case 35:
            return 'Solo'
        default:
            return ''
    }
}