import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Icon from '../../../../components/icon/Icon';
import './textEditor.css';
import { useCurrentEditor } from "@tiptap/react";
export default function MenuBar() {
    const { editor } = useCurrentEditor();
    if (!editor) {
        return null;
    }
    return (_jsxs("div", { className: "control-group", children: [_jsxs("div", { className: "button-group", children: [_jsx("button", { onClick: () => editor.chain().focus().toggleBold().run(), disabled: !editor.can().chain().focus().toggleBold().run(), className: editor.isActive('bold') ? 'is-active' : '', children: _jsx("strong", { children: "Bold" }) }), _jsx("button", { onClick: () => editor.chain().focus().toggleItalic().run(), disabled: !editor.can().chain().focus().toggleItalic().run(), className: editor.isActive('italic') ? 'is-active' : '', children: _jsx("em", { children: "Italic" }) }), _jsx("button", { onClick: () => editor.chain().focus().toggleStrike().run(), disabled: !editor.can().chain().focus().toggleStrike().run(), className: editor.isActive('strike') ? 'is-active' : '', children: _jsx("s", { children: "Strike" }) })] }), _jsxs("div", { className: "button-group", children: [_jsx("button", { onClick: () => editor.chain().focus().toggleHeading({ level: 1 }).run(), className: editor.isActive('heading', { level: 1 }) ? 'is-active' : '', children: "H1" }), _jsx("button", { onClick: () => editor.chain().focus().toggleHeading({ level: 2 }).run(), className: editor.isActive('heading', { level: 2 }) ? 'is-active' : '', children: "H2" }), _jsx("button", { onClick: () => editor.chain().focus().toggleHeading({ level: 3 }).run(), className: editor.isActive('heading', { level: 3 }) ? 'is-active' : '', children: "H3" }), _jsx("button", { onClick: () => editor.chain().focus().toggleHeading({ level: 4 }).run(), className: editor.isActive('heading', { level: 4 }) ? 'is-active' : '', children: "H4" }), _jsx("button", { onClick: () => editor.chain().focus().toggleHeading({ level: 5 }).run(), className: editor.isActive('heading', { level: 5 }) ? 'is-active' : '', children: "H5" })] }), _jsxs("div", { className: "button-group", children: [_jsx("button", { onClick: () => editor.chain().focus().toggleBulletList().run(), className: editor.isActive('bulletList') ? 'is-active' : '', children: _jsx(Icon, { iconName: 'bulletList', color: 'black' }) }), _jsx("button", { onClick: () => editor.chain().focus().toggleOrderedList().run(), className: editor.isActive('orderedList') ? 'is-active' : '', children: _jsx(Icon, { iconName: 'numberedList', color: 'black' }) })] }), _jsxs("div", { className: "button-group", children: [_jsx("button", { onClick: () => editor.chain().focus().undo().run(), disabled: !editor.can().chain().focus().undo().run(), children: _jsx(Icon, { iconName: 'backward', color: 'black' }) }), _jsx("button", { onClick: () => editor.chain().focus().redo().run(), disabled: !editor.can().chain().focus().redo().run(), children: _jsx(Icon, { iconName: 'forward', color: 'black' }) })] })] }));
}
