-- 5 Example Monsters for Bonfire Bestiary development
-- Run: psql -U bestiary -d bestiary -f backend/server/db/seed/seed-example-monsters.sql

BEGIN;

INSERT INTO bbindividualbeast (name, intro, habitat, ecology, senses, diet, size, patreon, canplayerview, rarity, role, secondaryrole, socialrole, skillrole, plural, tactics, sp_atk, sp_def, atk_conf, def_conf, atk_skill, def_skill, combatskulls, socialskulls, skillskulls, combatpoints, socialpoints, skillpoints, hash)
VALUES
(
    'Ashenwyrm',
    '<p>A serpentine dragon wreathed in smoldering embers, the Ashenwyrm dwells in volcanic tunnels and scorched wastelands. Its scales are blackened obsidian, cracked with veins of molten light. When enraged, its body erupts in gouts of flame that can melt stone.</p>',
    '<p>Volcanic caves, lava tubes, and scorched badlands. Ashenwyrms prefer geothermally active regions where they can bask in natural heat.</p>',
    '<p>Long and sinuous with a flattened, wedge-shaped head. Its obsidian-black scales are lined with cracks that glow orange-red. Two vestigial wings fold tight against its body. Its tail ends in a cluster of crystallized magma.</p>',
    '<p>Tremorsense 60ft, Darkvision 120ft. Can detect heat signatures through solid rock up to 30ft thick.</p>',
    '<p>Feeds onite minerals and calcium-rich stones. Will consume metal weapons and armor when available.</p>',
    'Large', 0, true, 4,
    'Striker', 'Controller', 'Intimidator', 'Ambusher',
    'Ashenwyrms',
    '<p>Opens with a burrowing ambush, erupting from below to scatter enemies. Focuses fire breath on clustered foes, then coils around isolated targets.</p>',
    '<p>Magma Spit: Ranged attack that leaves burning patches on the ground; On a Trauma Check, the target takes +2 Pos pressure and its armor gains 1 Wear.</p>',
    '<p>Heat Shimmer: When the Ashenwyrm Parries an attack, the attacker suffers Fatigue And Stress from the furnace glare.</p>',
    '<p>Smoldering Ultimatum: In a Confrontation, invokes volcanic Mem to apply Stress to a foe that refuses to back down.</p>',
    '<p>Obsidian Poise: On Trauma Check language or threats, the Ashenwyrm turns fear into +2 Pos for its next reply.</p>',
    '<p>Faultline Pursuit: During a Challenge, rolls dX! as tremors split the route; failures add X Wear to exposed gear.</p>',
    '<p>Lava Tube Recovery: Burns Endurance to clear Fatigue and gain Recovery before continuing the Challenge.</p>',
    5, 3, 4, 12, 6, 8,
    'ashenwyrm-001'
),
(
    'Boggart, Thornback',
    '<p>A squat, moss-covered fey creature that haunts marshlands and overgrown ruins. The Thornback Boggart is covered in sharp bramble-like spines that it can launch at prey. Despite its small size, it is cunning and territorial.</p>',
    '<p>Swamps, bogs, overgrown ruins, and dense thickets. Thornback Boggarts build nests from woven thorns in hollow trees or beneath fallen logs.</p>',
    '<p>Roughly 3 feet tall with mottled green-brown skin. Its back and shoulders bristle with wooden thorns. Large yellow eyes with slit pupils peer out from beneath a crown of tangled roots.</p>',
    '<p>Darkvision 60ft. Keen Smell. Can sense vibrations through standing water within 30ft.</p>',
    '<p>Omnivorous scavenger. Prefers insects, small fish, and fungi. Will eat carrion or raid travelers'' rations.</p>',
    'Small', 0, true, 2,
    'Skirmisher', 'Lurker', 'Trickster', 'Trapper',
    'Boggarts',
    '<p>Uses guerrilla tactics--hit and run from concealment. Launches thorn volleys then retreats into difficult terrain where larger foes cannot follow.</p>',
    '<p>Thorn Volley: Launches a spray of barbed thorns; On Trauma Check, barbs twist deeper and add X Wear to shields.</p>',
    '<p>Briar Armor: When the Boggart Parries an attack, brambles snag the weapon and inflict 1 Wear.</p>',
    '<p>Needling Taunt: In a Confrontation, mocks a target until Stress and Fatigue make retreat tempting.</p>',
    '<p>Mud-Slick Deflection: Spend Mem to ignore the first +2 Pos gained against it in a Confrontation.</p>',
    '<p>Snare Path: During a Challenge, hidden loops force dX! checks or drain Endurance.</p>',
    '<p>Bogbound Recovery: Uses reed beds for Recovery, removing Fatigue after a failed Challenge defense.</p>',
    2, 2, 3, 4, 3, 6,
    'boggart-thornback-001'
),
(
    'Cinderstag',
    '<p>A majestic cervid creature whose antlers perpetually smolder with pale fire. The Cinderstag is a guardian spirit of ancient forests recovering from wildfire. It is generally peaceful but fiercely protective of regrowth areas.</p>',
    '<p>Recovering forests, charred meadows, and the edges of firebreaks. Often found near young saplings growing from scorched earth.</p>',
    '<p>The size of a large elk with ash-grey fur that fades to white at the extremities. Its branching antlers glow with a soft amber flame that does not burn living wood. Hoofprints leave small patches of fertile ash.</p>',
    '<p>Darkvision 90ft. Can sense fire and heat within 1 mile. Tremorsense 30ft through root networks.</p>',
    '<p>Herbivore. Feeds on charcoal, ash, and the first green shoots that emerge after a fire.</p>',
    'Large', 0, true, 3,
    'Defender', 'Leader', 'Guardian', 'Sentinel',
    'Cinderstags',
    '<p>Prefers to warn intruders away with displays of flame before resorting to violence. Charges with burning antlers and uses hooves to create walls of fire between threats and the forest.</p>',
    '<p>Ember Charge: A rushing antler attack that ignites the target; On a Trauma Check, the target is Trauma''d by ancestral fire.</p>',
    '<p>Ashen Ward: Allies within 15ft gain Vitality against flame and reduce incoming Wear by 1.</p>',
    '<p>Guardian Rebuke: In a Confrontation, demands trespassers withdraw and adds +2 Pos when defending regrowth.</p>',
    '<p>Quiet Resolve: Converts Stress into calm Mem, blunting hostile Confrontation attacks.</p>',
    '<p>Rootfire Trail: During a Challenge, creates burning guide marks that grant Recovery to allies who keep pace.</p>',
    '<p>Last Grove Stand: Spends Endurance to absorb Fatigue for a companion during Challenge defense.</p>',
    4, 4, 3, 8, 8, 5,
    'cinderstag-001'
),
(
    'Gloomweaver',
    '<p>A spider-like aberration that spins webs of solidified shadow. The Gloomweaver lurks in places where darkness pools unnaturally--abandoned mines, sealed crypts, and the spaces between worlds. Its bite drains not blood but light itself.</p>',
    '<p>Deep underground caverns, abandoned mines, sealed crypts, and any location where natural darkness is unusually deep. Avoids direct sunlight.</p>',
    '<p>Eight-legged with a body of pure matte black that seems to absorb surrounding light. Its eight eyes glow a dim violet. Shadow trails behind it like ink in water. Approximately the size of a large dog.</p>',
    '<p>Blindsight 60ft. Darkvision 120ft. Can sense light sources within 300ft and is drawn to extinguish them.</p>',
    '<p>Feeds on ambient light and the life-force of creatures caught in its shadow webs.</p>',
    'Medium', 0, true, 3,
    'Lurker', 'Controller', 'Deceiver', 'Ambusher',
    'Gloomweavers',
    '<p>Extinguishes light sources first, then attacks from darkness. Wraps shadow webs around isolated targets to restrain and drain them. Retreats if exposed to bright light.</p>',
    '<p>Shadow Bite: Melee attack that reduces the target''s darkvision range; On Trauma Check, the bite also drains Vitality.</p>',
    '<p>Light Eater: Can suppress magical and mundane light within 30ft, gaining Recovery when it Parries an attack in darkness.</p>',
    '<p>Whisper Web: In a Confrontation, threads stolen secrets through Mem to impose Stress.</p>',
    '<p>Blank Face: Takes +2 Pos on defense when Confrontation pressure relies on fear or shame.</p>',
    '<p>Null-Lantern Maze: During a Challenge, rolls dX! for false exits that add Fatigue to pursuers.</p>',
    '<p>Silken Shelter: Converts X Wear on its webbing into Endurance for Challenge defense.</p>',
    3, 2, 4, 6, 4, 8,
    'gloomweaver-001'
),
(
    'Ironhide Troll',
    '<p>A massive, heavily armored troll whose skin has calcified into overlapping plates of iron-hard stone. Unlike its regenerating cousins, the Ironhide Troll has traded healing for near-impervious defense. It is slow but devastatingly powerful.</p>',
    '<p>Mountain passes, rocky highlands, and ancient bridge crossings. Ironhide Trolls are territorial and often claim chokepoints as their domain.</p>',
    '<p>Stands 12 feet tall with a hunched posture. Its grey-brown skin is covered in thick, overlapping plates resembling rusted iron. Small, deep-set eyes glow faintly orange. Its oversized fists can shatter stone.</p>',
    '<p>Darkvision 60ft. Tremorsense 30ft. Poor eyesight but excellent hearing.</p>',
    '<p>Carnivorous. Prefers large game but will eat anything organic. Known to demand tolls of food from travelers.</p>',
    'Huge', 0, true, 5,
    'Brute', 'Defender', 'Bully', 'Enforcer',
    'Ironhide Trolls',
    '<p>Stands its ground and absorbs punishment. Uses the terrain to funnel enemies into melee range. Throws boulders at distant foes, then closes to crush them.</p>',
    '<p>Boulder Hurl: Ranged attack with a massive thrown stone; On Trauma Check, targets are knocked prone and gain Fatigue.</p>',
    '<p>Iron Skin: Reduces all physical damage by a flat amount; weapons gain 1 Wear when the Troll Parries an attack.</p>',
    '<p>Toll Demand: In a Confrontation, threatens the road with +2 Pos unless travelers pay tribute.</p>',
    '<p>Stony Silence: Ignores Stress from insults and spends Mem to hold its ground.</p>',
    '<p>Pass Breaker: During a Challenge, its thrown rubble creates X Wear on carts and climbing tools.</p>',
    '<p>Mountain Endurance: Uses huge Vitality and Endurance to turn Fatigue into slow Recovery.</p>',
    6, 3, 2, 14, 5, 4,
    'ironhide-troll-001'
)
ON CONFLICT DO NOTHING;

WITH role_seed (
    id, beast_hash, vitality, hash, name, role, attack, defense, secondaryrole, combatpoints, stressstrength,
    panicstrength, cautionstrength, socialrole, socialpoints, skillrole, skillpoints, socialsecondary, size, fatiguestrength,
    largeweapons, mental, knockback, singledievitality, noknockback, rollundertrauma, attack_skill, defense_skill, attack_conf,
    defense_conf, isIncorporeal, weaponbreakagevitality, hasarchetypes, hasmonsterarchetypes, skillsecondary
) AS (
    VALUES
    (
        'ashenwyrm-brood-scorcher',
        'ashenwyrm-001',
        null,
        'ashenwyrm-brood-scorcher-001',
        'Brood Scorcher',
        'Artillery',
        '<p>Blistering Lance: Fires a narrow jet of white-hot slag; on a Trauma Check, armor gains 1 Wear.</p>',
        '<p>Furnace Coil: Parries by wrapping the attacker in radiant heat, forcing Fatigue on a failed retreat.</p>',
        'Veteran',
        11,
        null,
        null,
        null,
        'Zealot',
        7,
        'Survivalist',
        8,
        'Officer',
        'Large',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Cinder Trail: Reads ash drifts and heat scars to pursue prey through broken tunnels.</p>',
        '<p>Cooling Instinct: Buries itself under slag to shed Fatigue before the next push.</p>',
        '<p>Hoard Oath: Invokes the brood''s claim over a cavern to gain +2 Pos against trespassers.</p>',
        '<p>Molten Stare: Ignores Stress from threats while defending eggs or treasure.</p>',
        false,
        false,
        false,
        false,
        'Veteran'
    ),
    (
        'ashenwyrm-caldera-sentinel',
        'ashenwyrm-001',
        null,
        'ashenwyrm-caldera-sentinel-001',
        'Caldera Sentinel',
        'Defender',
        '<p>Obsidian Sweep: Knocks nearby foes away with a crystal-studded tail; shields gain 1 Wear.</p>',
        '<p>Lava Bank: Raises a ridge of cooling stone, reducing incoming pressure from the front.</p>',
        'Champion',
        14,
        null,
        null,
        null,
        'Obdurate',
        9,
        'Strategist',
        7,
        'Veteran',
        'Huge',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Vent Map: Uses heat plumes to predict stable paths through an eruption.</p>',
        '<p>Stone Patience: Waits out bad footing, turning a failed route into a defensible chokepoint.</p>',
        '<p>Territorial Warning: Holds the mouth of a tunnel and dares rivals to cross.</p>',
        '<p>Basalt Calm: Converts insults and displays into time for reinforcements to arrive.</p>',
        false,
        false,
        false,
        false,
        'Veteran'
    ),
    (
        'ashenwyrm-ember-hatchling',
        'ashenwyrm-001',
        null,
        'ashenwyrm-ember-hatchling-001',
        'Ember Hatchling',
        'Skirmisher',
        '<p>Spark Snap: Darts in with a burning bite, then slips behind loose stone.</p>',
        '<p>Ash Cloud: Kicks up choking dust to spoil aim and break line of sight.</p>',
        'Lesser',
        5,
        null,
        null,
        null,
        'Bully',
        3,
        'Athlete',
        4,
        'Lesser',
        'Medium',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Crack Runner: Squeezes through vents and rubble that larger creatures cannot use.</p>',
        '<p>Warm Nest: Recovers Endurance when it reaches hot stone or an ember pile.</p>',
        '<p>Piping Hiss: Tries to sound larger than it is, buying time for the brood.</p>',
        '<p>Sudden Retreat: Drops bravado the moment pressure turns serious.</p>',
        false,
        false,
        false,
        false,
        'Lesser'
    ),
    (
        'boggart-briar-slinger',
        'boggart-thornback-001',
        null,
        'boggart-briar-slinger-001',
        'Briar Slinger',
        'Artillery',
        '<p>Hooked Thorn: Pins sleeves, straps, and exposed gear; on a Trauma Check, the target gains Fatigue.</p>',
        '<p>Root Duck: Drops under brambles, making pursuit cost Endurance.</p>',
        'Lesser',
        4,
        null,
        null,
        null,
        'Charmer',
        4,
        'Street-Rat',
        5,
        'Lesser',
        'Small',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Scrap Cache: Produces stolen wire, hooks, and trash to improvise a way through obstacles.</p>',
        '<p>Foxhole Memory: Remembers every muddy hiding place within its patch of bog.</p>',
        '<p>False Friend: Offers directions that keep rivals talking while the thorns close in.</p>',
        '<p>Wide-Eyed Plea: Plays harmless until an enemy wastes their best leverage.</p>',
        false,
        false,
        false,
        false,
        'Lesser'
    ),
    (
        'boggart-mire-rake',
        'boggart-thornback-001',
        null,
        'boggart-mire-rake-001',
        'Mire Rake',
        'Skirmisher',
        '<p>Mud Slash: Opens shallow cuts with a thorn knife and retreats into sucking ground.</p>',
        '<p>Reed Screen: Vanishes behind reeds, forcing attackers to spend position finding it.</p>',
        'Veteran',
        7,
        null,
        null,
        null,
        'Bully',
        5,
        'Survivalist',
        6,
        'Veteran',
        'Small',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Marsh Gauge: Knows which tussocks hold and which sink.</p>',
        '<p>Bitter Roots: Chews numbing roots to ignore Fatigue until the chase ends.</p>',
        '<p>Territory Spite: Names every stolen berry and broken nest as cause for vengeance.</p>',
        '<p>Mean Little Grin: Treats threats as proof that its traps are working.</p>',
        false,
        false,
        false,
        false,
        'Veteran'
    ),
    (
        'boggart-thorn-nest-elder',
        'boggart-thornback-001',
        null,
        'boggart-thorn-nest-elder-001',
        'Thorn-Nest Elder',
        'Defender',
        '<p>Snarl of Canes: Turns the nest wall into a lashing barrier of green wood.</p>',
        '<p>Woven Thorns: Lets the nest take the hit, adding Wear to any weapon that follows through.</p>',
        'Officer',
        8,
        null,
        null,
        null,
        'Instructor',
        8,
        'Loremaster',
        7,
        'Officer',
        'Small',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Old Bog Lore: Recites routes, omens, and taboos from memory.</p>',
        '<p>Patient Snare: Lets impatient pursuers tire themselves before springing the path.</p>',
        '<p>Nest Law: Quotes boggart custom until younger fey fall in line.</p>',
        '<p>Rooted Scowl: Answers mockery with silence and a harder stare.</p>',
        false,
        false,
        false,
        false,
        'Veteran'
    ),
    (
        'cinderstag-grove-warden',
        'cinderstag-001',
        null,
        'cinderstag-grove-warden-001',
        'Grove Warden',
        'Defender',
        '<p>Antler Gate: Interposes burning antlers to stop a charge cold.</p>',
        '<p>Ash Circle: Stamps a protective ring that dulls incoming force and sparks warning light.</p>',
        'Officer',
        10,
        null,
        null,
        null,
        'Advocate',
        10,
        'Strategist',
        8,
        'Officer',
        'Large',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Firebreak Plan: Chooses routes that protect saplings and isolate threats.</p>',
        '<p>Measured Pace: Keeps allies moving without exhausting the weakest traveler.</p>',
        '<p>Mercy Terms: Offers a clear path out before invoking the forest''s wrath.</p>',
        '<p>Ancient Calm: Lets hostile words burn out before answering.</p>',
        false,
        false,
        false,
        false,
        'Veteran'
    ),
    (
        'cinderstag-ember-courser',
        'cinderstag-001',
        null,
        'cinderstag-ember-courser-001',
        'Ember Courser',
        'Shock',
        '<p>Dawn Charge: Crosses open ground in a flare of pale fire, scattering unsteady foes.</p>',
        '<p>Smoke Veil: Leaves a low cloud of warm ash between itself and pursuit.</p>',
        'Veteran',
        9,
        null,
        null,
        null,
        'Empath',
        8,
        'Athlete',
        9,
        'Veteran',
        'Large',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Long Run: Carries a warning across burned woodland without losing pace.</p>',
        '<p>Breath of Coals: Shares warmth with exhausted allies during a hard march.</p>',
        '<p>Gentle Warning: Reads fear in trespassers and steers them away from worse danger.</p>',
        '<p>Soft Hoofstep: Refuses bait meant to turn a warning into needless violence.</p>',
        false,
        false,
        false,
        false,
        'Veteran'
    ),
    (
        'cinderstag-ash-sapling',
        'cinderstag-001',
        null,
        'cinderstag-ash-sapling-001',
        'Ash Sapling',
        'Skirmisher',
        '<p>Flicker Kick: Strikes with a quick hoof and bounds behind older guardians.</p>',
        '<p>Kindling Leap: Escapes over low flame that heavier foes hesitate to cross.</p>',
        'Lesser',
        5,
        null,
        null,
        null,
        'Enabler',
        5,
        'Survivalist',
        5,
        'Lesser',
        'Medium',
        null,
        null,
        null,
        0,
        false,
        false,
        0,
        '<p>Green Shoot Sense: Finds new growth and safe browse in a burned field.</p>',
        '<p>Herd Shadow: Recovers when it can keep an elder Cinderstag in sight.</p>',
        '<p>Bright Trust: Coaxes hesitant allies to follow the herd.</p>',
        '<p>Startled Grace: Converts sudden pressure into a quick retreat.</p>',
        false,
        false,
        false,
        false,
        'Lesser'
    )
)
INSERT INTO bbroles (id, beastid, vitality, hash, name, role, attack, defense, secondaryrole, combatpoints, stressstrength,
    panicstrength, cautionstrength, socialrole, socialpoints, skillrole, skillpoints, socialsecondary, size, fatiguestrength,
    largeweapons, mental, knockback, singledievitality, noknockback, rollundertrauma, attack_skill, defense_skill, attack_conf,
    defense_conf, isIncorporeal, weaponbreakagevitality, hasarchetypes, hasmonsterarchetypes, skillsecondary)
SELECT role_seed.id, b.id, role_seed.vitality, role_seed.hash, role_seed.name, role_seed.role, role_seed.attack, role_seed.defense,
    role_seed.secondaryrole, role_seed.combatpoints, role_seed.stressstrength, role_seed.panicstrength, role_seed.cautionstrength,
    role_seed.socialrole, role_seed.socialpoints, role_seed.skillrole, role_seed.skillpoints, role_seed.socialsecondary, role_seed.size,
    role_seed.fatiguestrength, role_seed.largeweapons, role_seed.mental, role_seed.knockback, role_seed.singledievitality,
    role_seed.noknockback, role_seed.rollundertrauma, role_seed.attack_skill, role_seed.defense_skill, role_seed.attack_conf,
    role_seed.defense_conf, role_seed.isIncorporeal, role_seed.weaponbreakagevitality, role_seed.hasarchetypes,
    role_seed.hasmonsterarchetypes, role_seed.skillsecondary
FROM role_seed
JOIN bbindividualbeast b ON b.hash = role_seed.beast_hash
ON CONFLICT DO NOTHING;

WITH attack_seed (seed_hash, role_hash, display_index, situation, reference) AS (
    VALUES
    ('ashenwyrm-001', NULL, 0, 'At Range', 'Magma Spit: spits molten slag that leaves burning ground; on a Trauma Check, the target takes +2 Pos pressure and its armor gains 1 Wear.'),
    ('ashenwyrm-001', NULL, 1, 'In Melee', 'Ember Coil: wraps an isolated target in superheated scales, forcing them to spend position escaping the burn.'),
    ('boggart-thornback-001', NULL, 0, 'From Concealment', 'Thorn Volley: launches a spray of barbed thorns; on a Trauma Check, barbs twist deeper and add X Wear to shields.'),
    ('boggart-thornback-001', NULL, 1, 'In the Mire', 'Mud Hook: drags ankles and pack straps through sucking mud, costing Endurance before the boggart slips away.'),
    ('cinderstag-001', NULL, 0, 'Defending the Grove', 'Ember Charge: rushes with burning antlers; on a Trauma Check, the target is Trauma''d by ancestral fire.'),
    ('cinderstag-001', NULL, 1, 'Protecting Allies', 'Hoof-Flare: stamps a crescent of pale fire that drives foes back from injured companions.'),
    ('gloomweaver-001', NULL, 0, 'In Darkness', 'Shadow Bite: bites from a pool of shadow, reducing the target''s darkvision range; on a Trauma Check, the bite also drains Vitality.'),
    ('gloomweaver-001', NULL, 1, 'From Webbing', 'Umbral Snare: lashes with shadow silk that pins light sources and adds Fatigue to anyone tearing free.'),
    ('ironhide-troll-001', NULL, 0, 'At Range', 'Boulder Hurl: throws a massive stone; on a Trauma Check, targets are knocked prone and gain Fatigue.'),
    ('ironhide-troll-001', NULL, 1, 'In Melee', 'Plate-Fist Smash: hammers armor and shields with stone-hard knuckles, adding 1 Wear on a hard impact.'),
    ('ashenwyrm-001', 'ashenwyrm-brood-scorcher-001', 0, 'At Range', 'Blistering Lance: fires a narrow jet of white-hot slag; on a Trauma Check, armor gains 1 Wear.'),
    ('ashenwyrm-001', 'ashenwyrm-brood-scorcher-001', 1, 'When Pressed', 'Ashen Backdraft: vents a cone of hot ash behind itself to punish pursuit and cover a retreat.'),
    ('ashenwyrm-001', 'ashenwyrm-caldera-sentinel-001', 0, 'Holding Ground', 'Obsidian Sweep: knocks nearby foes away with a crystal-studded tail; shields gain 1 Wear.'),
    ('ashenwyrm-001', 'ashenwyrm-caldera-sentinel-001', 1, 'At a Chokepoint', 'Basalt Crush: pins a foe against stone with its shoulder, trading speed for brutal control.'),
    ('ashenwyrm-001', 'ashenwyrm-ember-hatchling-001', 0, 'Skirmishing', 'Spark Snap: darts in with a burning bite, then slips behind loose stone.'),
    ('ashenwyrm-001', 'ashenwyrm-ember-hatchling-001', 1, 'Under Cover', 'Cinder Spit: spits a small ember into exposed gear, creating distraction before it flees.'),
    ('boggart-thornback-001', 'boggart-briar-slinger-001', 0, 'At Range', 'Hooked Thorn: pins sleeves, straps, and exposed gear; on a Trauma Check, the target gains Fatigue.'),
    ('boggart-thornback-001', 'boggart-briar-slinger-001', 1, 'From Hiding', 'Needle Rain: shakes a thicket loose, peppering a clustered group before ducking under roots.'),
    ('boggart-thornback-001', 'boggart-mire-rake-001', 0, 'Skirmishing', 'Mud Slash: opens shallow cuts with a thorn knife and retreats into sucking ground.'),
    ('boggart-thornback-001', 'boggart-mire-rake-001', 1, 'When Pursued', 'Bog Trip: hooks a boot from below the waterline and turns a chase into a scramble.'),
    ('boggart-thornback-001', 'boggart-thorn-nest-elder-001', 0, 'Defending the Nest', 'Snarl of Canes: turns the nest wall into a lashing barrier of green wood.'),
    ('boggart-thornback-001', 'boggart-thorn-nest-elder-001', 1, 'At Close Range', 'Root-Crook Jab: drives a hooked staff into straps and joints, opening allies to strike.'),
    ('cinderstag-001', 'cinderstag-grove-warden-001', 0, 'Defending the Grove', 'Antler Gate: interposes burning antlers to stop a charge cold.'),
    ('cinderstag-001', 'cinderstag-grove-warden-001', 1, 'Shielding Saplings', 'Ward Hoof: stamps a bright warning sigil that punishes foes who cross it.'),
    ('cinderstag-001', 'cinderstag-ember-courser-001', 0, 'Charging', 'Dawn Charge: crosses open ground in a flare of pale fire, scattering unsteady foes.'),
    ('cinderstag-001', 'cinderstag-ember-courser-001', 1, 'Circling Back', 'Smoke-Kick: wheels through warm ash, blinding a pursuer before breaking away.'),
    ('cinderstag-001', 'cinderstag-ash-sapling-001', 0, 'Skirmishing', 'Flicker Kick: strikes with a quick hoof and bounds behind older guardians.'),
    ('cinderstag-001', 'cinderstag-ash-sapling-001', 1, 'Fleeing Danger', 'Kindling Leap: springs over low flame and clips a foe that hesitates at the edge.')
)
INSERT INTO bbattacks (index, reference, tactic, situation, roleid, beastid)
SELECT
    attack_seed.display_index,
    attack_seed.reference,
    NULL,
    attack_seed.situation,
    role_match.id,
    beast.id
FROM attack_seed
JOIN bbindividualbeast beast ON beast.hash = attack_seed.seed_hash
LEFT JOIN bbroles role_match ON role_match.hash = attack_seed.role_hash
WHERE (attack_seed.role_hash IS NULL OR role_match.id IS NOT NULL)
AND NOT EXISTS (
    SELECT 1
    FROM bbattacks
    WHERE bbattacks.beastid = beast.id
    AND (bbattacks.roleid = role_match.id OR (bbattacks.roleid IS NULL AND role_match.id IS NULL))
    AND bbattacks.reference = attack_seed.reference
);

WITH defense_seed (seed_hash, display_index, defense_name, info, swarmbonus, armor, shield, eua, addsizemod, tdr) AS (
    VALUES
    ('ashenwyrm-001', 0, 'Obsidian Scales', '<p>Heat Shimmer: when the Ashenwyrm Parries an attack, the attacker suffers Fatigue and Stress from the furnace glare.</p>', false, '', '', false, true, false),
    ('boggart-thornback-001', 0, 'Briar Armor', '<p>Briar Armor: when the Boggart Parries an attack, brambles snag the weapon and inflict 1 Wear.</p>', false, '', '', false, true, false),
    ('cinderstag-001', 0, 'Ashen Ward', '<p>Ashen Ward: allies within 15ft gain Vitality against flame and reduce incoming Wear by 1.</p>', false, '', '', false, true, false),
    ('gloomweaver-001', 0, 'Light Eater', '<p>Light Eater: can suppress magical and mundane light within 30ft, gaining Recovery when it Parries an attack in darkness.</p>', false, '', '', false, true, false),
    ('ironhide-troll-001', 0, 'Iron Skin', '<p>Iron Skin: reduces all physical damage by a flat amount; weapons gain 1 Wear when the Troll Parries an attack.</p>', false, '', '', false, true, true)
),
missing_defense_seed AS (
    SELECT
        defense_seed.*,
        bbindividualbeast.id AS beastid
    FROM defense_seed
    JOIN bbindividualbeast ON bbindividualbeast.hash = defense_seed.seed_hash
    WHERE NOT EXISTS (
        SELECT 1
        FROM bbdefenses
        WHERE bbdefenses.beastid = bbindividualbeast.id
        AND bbdefenses.name = defense_seed.defense_name
    )
),
inserted_combat_stats AS (
    INSERT INTO bbcombatstats (
        beastid, roleid, piercingweapons, slashingweapons, crushingweapons, weaponsmallslashing,
        weaponsmallcrushing, weaponsmallpiercing, andslashing, andcrushing, flanks, alldefense,
        allaround, armorandshields, unarmored, attack, isspecial, eua, addsizemod, weapon, shield,
        armor, weaponname, rangeddefense, initiative, measure, recovery, showonlydefenses, weapontype,
        rangedistance, swarmbonus, adjustment, tdr, info
    )
    SELECT
        beastid, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, 'no', eua, addsizemod, '', shield,
        armor, defense_name, NULL, NULL, NULL, NULL, true, 'm',
        NULL, swarmbonus, 0, tdr, info
    FROM missing_defense_seed
    RETURNING id, beastid, weaponname
)
INSERT INTO bbdefenses (oldid, beastid, index, name)
SELECT
    inserted_combat_stats.id,
    inserted_combat_stats.beastid,
    missing_defense_seed.display_index,
    missing_defense_seed.defense_name
FROM inserted_combat_stats
JOIN missing_defense_seed
    ON missing_defense_seed.beastid = inserted_combat_stats.beastid
    AND missing_defense_seed.defense_name = inserted_combat_stats.weaponname;

COMMIT;
